In [2]:
import numpy as np

In [3]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
A.shape

(3, 2)

In [6]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
B = A.T

In [8]:
B

array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
B.shape

(2, 3)

In [10]:
B = np.ones((3,2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
A + B

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [12]:
A.shape
B.shape

(3, 2)

In [13]:
A.dot(B)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [14]:
A.dot(B.T)

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])